apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - coit-frontend-deployment.yaml
  - service-coit-frontend-lb.yaml

replicas:
- name: coit-frontend 
  count: 3

images:
- name: coitlearning/coit-frontend
  newName: coitlearning/coit-frontend
  newTag: 1.0.1

namespace: default
