apiVersion: apps/v1
kind: Deployment
metadata:
  name: coit-backend1
  labels:
    app: coit-backend1
spec:
  selector:
    matchLabels:
      app: coit-backend1
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: coit-backend1
    spec:
      containers:
      - image: coitlearning/coit-backend1:v3
        imagePullPolicy: IfNotPresent
        name: coit-backend1
        env:
          - name: SA_LOGIC_API_URL
            value: "http://coit-backend2"
        ports:
          - containerPort: 8080
