apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: coit-frontend
  labels:
    app: coit-frontend
spec:
  selector:
    matchLabels:
      app: coit-frontend
  replicas: 1                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: coit-frontend                                  # 6
    spec:
      volumes:
        - name: nginx-root
          persistentVolumeClaim:
            claimName: coit-frontend-fast
      containers:
        - image: coitlearning/coit-frontend:latest
          imagePullPolicy: IfNotPresent                         # 7
          name: coit-frontend
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: nginx-root