apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: coit-frontend
  labels:
    app: coit-frontend
spec:
  selector:
    matchLabels:
      app: coit-frontend
  replicas: 3                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: coit-frontend                                  # 6
    spec:
      containers:
        - image: coitlearning/coit-frontend:latest
          imagePullPolicy: IfNotPresent                         # 7
          name: coit-frontend
          ports:
            - containerPort: 80
          env:
            - name: JAVA_APP_URL
              valueFrom:
                configMapKeyRef:
                  name: coit-frontend-config
                  key: JAVA_URL
            - name: SMS_API
              valueFrom:
                configMapKeyRef:
                  name: values-from-props
                  key: sms_provider_api
